### ISSUE TITLE
optimize: Add CMA-ES optimization algorithm

### ISSUE THREAD

**Issue by agrimball** [gonum/optimize#180]
Described here: [link](https://en.wikipedia.org/wiki/CMA-ES)

Love the matrix library you guys provide though!

**Comment by btracey** [comment]
Thanks!

CMA-ES is on the mental list. It first requires figuring out the right abstraction layer for global optimization.

**Comment by btracey** [comment]
Okay, I have a working implementation. Waiting on https://github.com/gonum/gonum/pull/273 and one more follow-on pull request before the necessary framework is up.
