### ISSUE TITLE
optimize: Repo description should not end with a "."

### ISSUE THREAD

**Issue by jonlawlor** [gonum/optimize#189]
Repo descriptions are headings and should not include a "."

It is impossible to handle this change with a pull request and so this issue will be used for coordinating the change.  PTAL

**Comment by kortschak** [comment]
SGTM

**Comment by vladimir-ch** [comment]
How about changing the description to `Packages for solving minimization problems` ? It avoids saying "the optimum value" because often we don't find _the_ optimum value, and I like "problems" more than "functions" because "problem" is more accurate as it contains also the constraints. @btracey ?

**Comment by btracey** [comment]
SGTM

**Comment by jonlawlor** [comment]
Done
