### ISSUE TITLE
Method.Init() should not return IterationType

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/optimize#40]
Method.Init() should not return IterationType because there is simply no iteration to conclude. Moreover, the initial location should be dealt with before calling Method.Init() which should be invoked only if the initial location does not satisfy the convergence criteria.

**Comment by btracey** [comment]
As I mentioned in the other thread, in my mind IterationType is about the upcoming function evaluation. It should return a type. For example, NelderMead may need to construct its initial simplex. The first function evaluation is not the start of a MajorEvaluation, but instead an InitialIteration or something.

**Comment by vladimir-ch** [comment]
As I replied in the other thread, IterationType being about the upcoming function evaluation is natural and consistent with EvaluationType. In that case, Linesearch.Init() must be fixed to return MinorIteration, not MajorIteration as it does now.

I will close this and submit a new issue for fixing it.
