### ISSUE TITLE
github.com/gonum/optimize/bfgs.go:136: undefined: mat64.Inner

### ISSUE THREAD

**Issue by vbenso** [gonum/optimize#52]
I've just typed:
go get github.com/gonum/matrix/mat64
and 
go get github.com/gonum/optimize
is returning the following errors:
github.com/gonum/optimize/bfgs.go:136: undefined: mat64.Inner
github.com/gonum/optimize/bfgs.go:161: b.invHess.RankOne undefined (type *mat64.Dense has no field or method RankOne)

is there a specific fork from mat64 that I should be using?

**Comment by vbenso** [comment]
Sorry for being ignorant, using: go get -u github.com/gonum/matrix/mat64 , solved the problem after all. Didn't know about that flag.

**Comment by jonlawlor** [comment]
You may also want to use the -t flag so that test dependencies are fetched.
