### ISSUE TITLE
Think about moving test functions

### ISSUE THREAD

**Issue by btracey** [gonum/optimize#56]
I spend a lot of time working on optimization algorithms. I think our package will be great for this given that outside optimizers can take advantage of the full framework. One thing that I would like is to have a bunch of pre-defined functions that are already implemented with their gradients that I can use to experiment with. Well, we already have this -- the function suite @vladimir-ch put together. The problem with the current PR is that those functions are scheduled to be in optimize_test which is not importable. I would suggest that we have a "testopt" package that contains these functions, and possibly some form of tests. At the very least, if the functions themselves are in their own package, they could be used by anyone.

**Comment by vladimir-ch** [comment]
I agree with a "testopt" package and moving the test functions there. I think that I even mentioned such option in #28 at some point. Shall we go ahead with this?
